language: swift
osx_image: xcode9
xcode_project: Example/CenteredCollectionView.xcworkspace
xcode_schema: CenteredCollectionView_Tests
notifications:
  disabled: true
script:
  - xcodebuild test -scheme CenteredCollectionView -destination "OS=11.3,name=iPhone SE" -sdk iphonesimulator11.3 | xcpretty -c
